version: '3.4'

services:
  currency-conversion.web:
    environment:
      - DB_CONNECTION_STRING=host=postgres_image;port=5432;database=currencyDB;username=admin;password=admin
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  currency-conversion.worker:
    environment:
      - DB_CONNECTION_STRING=host=postgres_image;port=5432;database=currencyDB;username=admin;password=admin
  